management:
  health:
    mail:
      enabled: false
  server:
    servlet:
      context-path: /actuator

mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
server:
  port: 8088
  servlet:
    context-path: /tcoiss-job-admin
spring:
  redis:
    host: 124.71.141.121
    port: 6379
    password: 123456
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 10000
      idle-timeout: 30000
      max-lifetime: 900000
      maximum-pool-size: 30
      minimum-idle: 10
      pool-name: HikariCP
    password: 123456
    username: root
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://124.71.141.121:3306/sp_system?useSSL=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai

  freemarker:
    charset: UTF-8
    request-context-attribute: request
    settings:
      number_format: 0.##########
    suffix: .ftl
    templateLoaderPath: classpath:/templates/
  mail:
    host: smtp.qq.com
    port: 25
    username: 1469803698@qq.com
    from: 1469803698@qq.com
    password: 123456zw
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: true
            required: true

  mvc:
    servlet:
      load-on-startup: 0
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
xxl:
  job:
    accessToken: ''
    i18n: zh_CN
    logretentiondays: 30
    triggerpool:
      fast:
        max: 200
      slow:
        max: 100

