spring:
  redis:
    host: localhost
    port: 6379
    password: 123456
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        # 认证中心
        - id: tcoiss-auth
          uri: lb://tcoiss-auth
          predicates:
            - Path=/auth/**
          filters:
            # 验证码处理
            - CacheRequestFilter
            - ValidateCodeFilter
            - StripPrefix=1
        # 代码生成
        - id: tcoiss-gen
          uri: lb://tcoiss-gen
          predicates:
            - Path=/code/**
          filters:
            - StripPrefix=1
        # 系统模块
        - id: tcoiss-system
          uri: lb://tcoiss-system
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=1
        # 文件服务
        - id: tcoiss-file
          uri: lb://tcoiss-file
          predicates:
            - Path=/file/**
          filters:
            - StripPrefix=1
        # 数据库集成服务
        - id: tcoiss-dbsource
          uri: lb://tcoiss-dbsource
          predicates:
            - Path=/dbsource/**
          filters:
            - StripPrefix=1

        # web集成服务
        - id: tcoiss-webservice
          uri: lb://tcoiss-webservice
          predicates:
            - Path=/webservice/**
          filters:
            - StripPrefix=1

# 不校验白名单
ignore:
  whites:
    - /auth/logout
    - /auth/login
    - /*/v2/api-docs
    - /csrf
